
TOP_INDIAN_NEWS_SITES = [
    {"name": "Times of India",
     "url": "https://timesofindia.indiatimes.com/", "language": "English"},
    {"name": "NDTV", "url": "https://www.ndtv.com/", "language": "English"},
    {"name": "India Today", "url": "https://www.indiatoday.in/",
             "language": "English"},
    {"name": "Hindustan Times",
             "url": "https://www.hindustantimes.com/", "language": "English"},
    {"name": "The Hindu", "url": "https://www.thehindu.com/",
             "language": "English"},
    {"name": "News18", "url": "https://www.news18.com/", "language": "English"},
    {"name": "Indian Express", "url": "https://indianexpress.com/",
             "language": "English"},
    {"name": "Economic Times",
             "url": "https://economictimes.indiatimes.com/", "language": "English"},
    {"name": "Dainik Jagran",
             "url": "https://www.jagran.com/", "language": "Hindi"},
    {"name": "Dainik Bhaskar",
             "url": "https://www.bhaskar.com/", "language": "Hindi"},
    {"name": "Aaj Tak", "url": "https://www.aajtak.in/", "language": "Hindi"},
    {"name": "ABP News", "url": "https://www.abplive.com/", "language": "Hindi"},
    {"name": "Zee News", "url": "https://zeenews.india.com/", "language": "Hindi"},
    {"name": "TV9 Bharatvarsh",
             "url": "https://www.tv9hindi.com/", "language": "Hindi"},
    {"name": "Republic World",
             "url": "https://www.republicworld.com/", "language": "English"},
    {"name": "Firstpost", "url": "https://www.firstpost.com/",
             "language": "English"},
    {"name": "Hindu BusinessLine",
             "url": "https://www.thehindubusinessline.com/", "language": "English"},
    {"name": "The Wire", "url": "https://thewire.in/", "language": "English"},
    {"name": "Scroll.in", "url": "https://scroll.in/", "language": "English"},
    {"name": "The Print", "url": "https://theprint.in/", "language": "English"},
    {"name": "LiveMint", "url": "https://www.livemint.com/",
             "language": "English"},
    {"name": "News24", "url": "https://news24online.com/", "language": "Hindi"},
    {"name": "Mathrubhumi", "url": "https://www.mathrubhumi.com/",
             "language": "Malayalam"},
    {"name": "Manorama Online",
             "url": "https://www.manoramaonline.com/", "language": "Malayalam"},
    {"name": "Anandabazar Patrika",
             "url": "https://www.anandabazar.com/", "language": "Bengali"},
    {"name": "Eenadu", "url": "https://www.eenadu.net/", "language": "Telugu"},
    {"name": "Lokmat", "url": "https://www.lokmat.com/", "language": "Marathi"},
    {"name": "Maharashtra Times",
             "url": "https://maharashtratimes.com/", "language": "Marathi"},
    {"name": "Loksatta", "url": "https://www.loksatta.com/",
             "language": "Marathi"},
    {"name": "Sakshi", "url": "https://www.sakshi.com/", "language": "Telugu"},
    {"name": "Rajasthan Patrika",
             "url": "https://www.patrika.com/", "language": "Hindi"},
    {"name": "Prabhat Khabar",
             "url": "https://www.prabhatkhabar.com/", "language": "Hindi"},
    {"name": "Punjab Kesari",
             "url": "https://www.punjabkesari.in/", "language": "Hindi"},
    {"name": "Divya Bhaskar", "url": "https://www.divyabhaskar.co.in/",
             "language": "Gujarati"},
    {"name": "Gujarat Samachar",
             "url": "https://www.gujaratsamachar.com/", "language": "Gujarati"},
    {"name": "Dinamalar", "url": "https://www.dinamalar.com/",
             "language": "Tamil"},
    {"name": "Dinamani", "url": "https://www.dinamani.com/", "language": "Tamil"},
    {"name": "Amarujala", "url": "https://www.amarujala.com/",
             "language": "Hindi"},
    {"name": "Saamana", "url": "https://www.saamana.com/",
             "language": "Marathi"},
    {"name": "Navbharat Times",
             "url": "https://navbharattimes.indiatimes.com/", "language": "Hindi"},
    {"name": "Business Standard",
             "url": "https://www.business-standard.com/", "language": "English"},
    {"name": "Financial Express",
             "url": "https://www.financialexpress.com/", "language": "English"},
    {"name": "Amar Ujala", "url": "https://www.amarujala.com/",
             "language": "Hindi"},
    {"name": "Kannada Prabha",
             "url": "https://www.kannadaprabha.com/", "language": "Kannada"},
    {"name": "Vijay Karnataka",
             "url": "https://vijaykarnataka.com/", "language": "Kannada"},
    {"name": "Prajavani", "url": "https://www.prajavani.net/",
             "language": "Kannada"},
    {"name": "Samaja", "url": "https://www.thesamaja.com/", "language": "Odia"},
    {"name": "Sambad", "url": "https://sambad.in/", "language": "Odia"},
    {"name": "The Tribune", "url": "https://www.tribuneindia.com/",
             "language": "English"},
    {"name": "Outlook India", "url": "https://www.outlookindia.com/",
             "language": "English"},
    # Additional news sources as requested
    {"name": "DD News", "url": "https://ddnews.gov.in/",
             "language": "English/Hindi"},
    {"name": "All India Radio", "url": "https://newsonair.gov.in/",
             "language": "English/Hindi"},
    {"name": "ScoopWhoop", "url": "https://www.scoopwhoop.com/",
             "language": "English"},
    {"name": "ANI", "url": "https://www.aninews.in/", "language": "English"},
    {"name": "Daily Hunt", "url": "https://m.dailyhunt.in/",
             "language": "Multi-language"},
    {"name": "Dinakaran", "url": "https://www.dinakaran.com/",
             "language": "Tamil"},
    {"name": "Latestly", "url": "https://www.latestly.com/",
             "language": "English"},
    {"name": "India.com", "url": "https://www.india.com/",
             "language": "English"},
    {"name": "Zee Business", "url": "https://www.zeebiz.com/",
             "language": "English"},
    {"name": "Jagran Josh", "url": "https://www.jagranjosh.com/",
             "language": "English"},
    {"name": "MoneyControl", "url": "https://www.moneycontrol.com/",
             "language": "English"},
    {"name": "The New Indian Express",
             "url": "https://www.newindianexpress.com/", "language": "English"},
    {"name": "Jansatta", "url": "https://www.jansatta.com/", "language": "Hindi"},
    {"name": "India TV", "url": "https://www.indiatvnews.com/",
             "language": "English/Hindi"},
    {"name": "Asianet News", "url": "https://www.asianetnews.com/",
             "language": "Malayalam"},
    {"name": "BusinessWorld", "url": "https://www.businessworld.in/",
             "language": "English"},
    {"name": "The Pioneer", "url": "https://www.dailypioneer.com/",
             "language": "English"}

]
